[pytest]
addopts = --import-mode=importlib
pythonpath = src/fr3_bolt_inspection_cell src/fr3_dual_bolt_cell src/fr3_control_panel
testpaths = src/fr3_bolt_inspection_cell/test src/fr3_dual_bolt_cell/test src/fr3_control_panel/test
